function plotCTFs

% Fig 2e in Foster et al. Psych Science

set(0,'DefaultAxesFontName', 'HelveticaNeue LT 57 Cn')
fs = 9; % size for axis numbers
labelSize = 10; % size for axis labels


% specify subjects to plot
subs = [1,2];%,3,7,8,9,10,11,12,14,15,16,17,18,19,20];
nSubs = length(subs);

% setup directories
root = pwd; out = 'AnalysisScripts';
dRoot = [root(1:end-length(out)),'Data/'];

% specify filename of data to plot
name = '1_SpatialTF.mat';

% Plot specs
nChans = 8; % number of location-selective channels
view3d = [90 90]; % view angle of 3d plots
lim = [-.05 0.7]; % limits on color map and channel response axis (was 0.6)
times = -500:4:1248;
nSamps = length(times);


% loop through participants and grab tf generated by forward model
for i = 1:nSubs
    sn = subs(i);
    fName = [name];
    load(fName)
    fois = ismember(em.bands,'Alpha');
    t_ctf(i,:,:,:) = squeeze(mean(mean(em.C2.total(fois,:,:,:,:,:),2),4));  % same for total data.
    
end

tctf = squeeze(mean(t_ctf)); % average across subjects

% open figure
FigHandle = figure('Position', [100, 100, 320, 460]); % size of the plot

% Setup plot axes
x = linspace(-180,180,nChans+1);
nTimes = size(tctf,1); nBins = length(x);
X = repmat(x',1,nTimes);
Y = repmat(times,nBins,1);

for bin = 1:8
    
    subplot(8,1,bin)
    tmp = squeeze(tctf(:,bin,:));
    tmp = tmp';
    tmp = circshift(tmp,5-bin); % circularly shift so on-channel is in position 5
     tmp = [tmp; tmp(1,:)]; % mirror the end point
    tmp = tmp';
%     imagesc([-500 1248],[-180 180],tmp);
%     set(gca,'FontName','Arial Narrow')
%      ax = gca;
%     if bin ~= 8
%         set(ax,'XTick',[])
%     else
%         set(ax,'XTick',[-500:500:1250])
%         xlabel({'Time (ms)'});
%     end
%      set(ax,'YTick',[-180 0 180])

surf(X,Y,tmp','EdgeColor','none','LineStyle','none','FaceLighting','phong')
shading interp
h=findobj('type','patch');
set(h,'linewidth',1)
hold on
set(gca, 'box','on')
set(gca,'color','none')
set(gca,'LineWidth',1.5,'TickDir','out');
set(gca,'FontSize',fs)
view(view3d)
axis([x(1) x(end) times(1) times(end) lim]);
ax = gca
    if bin ~= 8
        set(ax,'YTick',[])%set(ax,'YTick',[-500:500:1500])
    else
        set(ax,'YTick',[-500:500:1500])
        ylabel({'Time (ms)'}); set(get(gca,'ylabel'),'FontSize',labelSize);
    end
set(gca,'XTick',[-180:180:180])
caxis(lim)
end


% slopes = nan(8,nSubs,nSamps);
% 
% for bin = 1:8
%     % calculate slope values for each subject across time
%     for sub = 1:nSubs
%         for samp = 1:nSamps
%             dat = squeeze(t_ctf(sub,samp,bin,:));
%             dat = circshift(dat,5-bin);            % circularly shift based on the data;
%             x = 1:5;
%             d = [dat(1),mean([dat(2),dat(8)]),mean([dat(3),dat(7)]),mean([dat(4),dat(6)]),dat(5)];
%             fit = polyfit(x,d,1);
%             slopes(bin,sub,samp)= fit(1);
%         end
%     end
% end
%     
% x = squeeze(mean(slopes,2));
% 
% % Plot average CTF with bootstrapped SE
% FigHandle = figure('Position', [100, 100, 400, 450]); % size of the plot
% plot(times,x','LineWidth',1)
% ylim([-0.1 0.2])
% xlim([-500 1252])
% set(gca,'XTick',[-500:500:1250])
% set(gca, 'box','off')
% set(gca,'color','none')
% set(gca,'LineWidth',2,'TickDir','out');
% set(gca,'FontSize',fs)
% xlabel({'Times (ms)'}); set(get(gca,'xlabel'),'FontSize',fs,'FontWeight','bold')
% ylabel('CTF Slope'); set(get(gca,'ylabel'),'FontSize',fs,'FontWeight','bold')
%     
% end